# =========================
# WS SERVER
# =========================
server {
    listen 1010 proxy_protocol reuseport;
    server_name _;

    set_real_ip_from 127.0.0.1;
    real_ip_header proxy_protocol;

    client_max_body_size 0;
    keepalive_timeout 65s;
    keepalive_requests 10000;

    proxy_read_timeout 86400s;
    proxy_send_timeout 86400s;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_buffering off;

    location /vless {
        proxy_pass http://127.0.0.1:10001;
    }

    location /vmess {
        proxy_pass http://127.0.0.1:10002;
    }

    location /trojan-ws {
        proxy_pass http://127.0.0.1:10003;
    }

    location /ss-ws {
        proxy_pass http://127.0.0.1:10004;
    }

    location / {
        proxy_pass http://127.0.0.1:10015;
    }
}

# =========================
# gRPC SERVER
# =========================
server {
    listen 1013 http2 proxy_protocol reuseport;
    server_name _;

    set_real_ip_from 127.0.0.1;
    real_ip_header proxy_protocol;

    keepalive_timeout 65s;

    grpc_read_timeout 86400s;
    grpc_send_timeout 86400s;

    grpc_set_header Host $host;
    grpc_set_header X-Real-IP $remote_addr;
    grpc_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    location /vless-grpc {
        grpc_pass grpc://127.0.0.1:10005;
    }

    location /vmess-grpc {
        grpc_pass grpc://127.0.0.1:10006;
    }

    location /trojan-grpc {
        grpc_pass grpc://127.0.0.1:10007;
    }

    location /ss-grpc {
        grpc_pass grpc://127.0.0.1:10008;
    }
}

# =========================
# SSL STATIC / PANEL
# =========================
server {
    listen 81 ssl http2 reuseport;
    server_name _;

    ssl_certificate /etc/xray/xray.crt;
    ssl_certificate_key /etc/xray/xray.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers EECDH+CHACHA20:EECDH+AES128:EECDH+AES256;
    ssl_prefer_server_ciphers on;

    root /var/www/html;
    index index.html;
}